### ISSUE TITLE
How to see the changes made to R/helpers.R ?

### ISSUE THREAD

**Issue by jessielyons** [vibscc/DALI#10]
Hi DALI team,

Many thanks for your kind help changing the function ClonotypeToSequence to include the v_gene along with the Cdr3 aa annotation. However, when I made the change and reran the shiny script as follows, no change happens.

shiny::runApp('inst/shiny')

Is there a particular sequence of steps/re-run required to see the change in the clonotype table on the app? So far I see the same output in the app w/wo the change to the function. Any changes I make to the helpers.R code in your R directory, is not seen re-running shiny app as above.

Thanks again,
Jessie

**Comment by kverstae** [comment]
The problem is that that shiny application calls that function like this: `DALI:::ClonotypeToSequence()`.
It therefor looks for the function in DALI installed on your system and does not look at the changes you made in the source yourself.
To make it use your code, you will have to rebuild DALI from source, with your changes included. This can easily be done in Rstudio. There should be a Build tab somewhere (normally in the same pane as your environment) and there you should find a button 'Build & Reload' or 'Install and Restart' (or something similar). You can also press CTRL + SHIFT + B when you have the DALI project loaded in Rstudio.
After doing this, the DALI version installed on your system will include all changes you made to the code locally. The Shiny app should then pick up those changes and display the updated text in the CDR3 AA annotation.
