### ISSUE TITLE
Figure 5B - clonotype 12 example - missing light chain annotations?

### ISSUE THREAD

**Issue by jessielyons** [vibscc/DALI#8]
Dear DALI Team,

Again, great tool. Few questions

1) Attached I dug into the test data provided by the DALI team and extracted clonotype12 from the "filtered_contig_annotations.csv" and matched it the Figure5B of the table provided. Attached please see "Test.csv" containing just clonotype12 information.

Can you please clarify, why the two light chain annotations in bold below are not listed in Figure 5B?
IGHJ3_CARDSLNWDGAYW
**_IGKJ5_CQQRSSYPPTF_**
IGHJ3_CARDSLNWDGTYW
**_IGKJ5_CQQRSCYPPTF_**
IGKJ4_CVQGTHFPFTF
IGHJ3_CARDSLNWDGAFW
IGKJ4_CVQGTHFPFTF

2) How is the "pct.group" defined? How is it calculated?

Thanks,
Jessie

[Test.csv](https://github.com/vibscc/DALI/files/8664525/Test.csv)

**Comment by kverstae** [comment]
Hi Jessie,

1. This is because these sequences are considered 'secondary'. If you look at the data for clonotype 12 (table below, same as your CSV but a line seemed to be missing in it), you can see that 2 cells have 3 rows of information. Both of these cells have 2 light chains, which are both productive. If this happens, we consider the chain with the highest UMI count as 'primary' and the second one as 'secondary'. By default, you will only see the primary information in the tool and this then results in there only being 
'CVQGTHFPFTF' as light chain CDR3 sequence in that table in figure 5B.
You could run `DefaultChainVDJ(seuratObj) <- "secondary"` to look at the secondary chains, but this will then not show the information of the primary chains anymore.

| barcode | v_gene | j_gene | c_gene | cdr3 | umis | raw_clonotype_id |
| - | - | - | - | - | - | - |
| AGCTCTCCATGGAATA-1 | IGHV3-6 | IGHJ3 | IGHM | CARDSLNWDGAFW | 69 | clonotype12 |
| AGCTCTCCATGGAATA-1 | IGKV1-133 | IGKJ4 | IGKC | CVQGTHFPFTF | 66 | clonotype12 |
| CGTAGGCCATGTTGAC-1 | IGHV3-6 | IGHJ3 | IGHM | CARDSLNWDGAYW | 91 | clonotype12 |
| CGTAGGCCATGTTGAC-1 | IGKV4-57 | IGKJ5 | IGKC | CQQRSSYPPTF | 77 | clonotype12 |
| CGTAGGCCATGTTGAC-1 | IGKV1-133 | IGKJ4 | IGKC | CVQGTHFPFTF | 82 | clonotype12 |
| TTTGCGCGTCCGCTGA-1 | IGHV3-6 | IGHJ3 | IGHM | CARDSLNWDGTYW | 87 | clonotype12 |
| TTTGCGCGTCCGCTGA-1 | IGKV4-57 | IGKJ5 | IGKC | CQQRSCYPPTF | 63 | clonotype12 |
| TTTGCGCGTCCGCTGA-1 | IGKV1-133 | IGKJ4 | IGKC | CVQGTHFPFTF | 89 | clonotype12 |

2. pct.group is the percentage of the group (cluster, subsamples...) which has that clonotype. It is basically just the number of cells with that clonotype divided by the total number of cells in that group.

**Comment by kverstae** [comment]
Feel free to reopen the issue if this didn't answer your question!
